# Build the project using the Bitcraze builder docker image
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Weekly build to make sure dependencies are OK
    - cron:  '30 15 * * 5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Todo: add back "crazyradio2" when new protocol is reimplemented
        mode: [crazyradio2-CRPA-emulation]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: install just
      uses: extractions/setup-just@v3
    - name: Install uv
      uses: astral-sh/setup-uv@v6

    # Build only the CRPA emulation mode for now
    # TODO: add back new protocol
    - name: Build
      run: |
        uv venv
        source ./.venv/bin/activate

        just fetch-sdk
        just fetch-zephyr
        just build

        cp build/zephyr/crazyradio2.uf2 ${{ matrix.mode }}.uf2
        cp build/zephyr/crazyradio2.hex ${{ matrix.mode }}.hex

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.mode }}
        path: |
          ${{ matrix.mode }}.uf2
          ${{ matrix.mode }}.hex